# Generated by Django 3.2.7 on 2022-02-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_user_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_image',
            field=models.ImageField(blank=True, default='cover/network.jpg', null=True, upload_to='cover/'),
        ),
    ]
