# Generated by Django 3.2.7 on 2022-07-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_alter_user_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_image',
            field=models.ImageField(blank=True, default='cover/jaguar.jpg', null=True, upload_to='cover/'),
        ),
    ]
